import React, { useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useTaskContext } from "../context/taskContext";
import axios from "axios";

export default function Home({ data }) {
  const { setData } = useTaskContext();
  console.log(data);

  useEffect(() => {
    setData(data);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>im the next app</main>
    </div>
  );
}

export const getStaticProps = async () => {
  const response = await axios.get(
    "https://jsonplaceholder.typicode.com/users"
  );

  // console.log(response);

  const data = response.data;
  console.log(data);

  return {
    props: { data: data },
  };
};
